### ISSUE TITLE
syntax error in control.py + error when extracting labels in treemodel.py?

### ISSUE THREAD

**Issue by melisaolave** [jeetsukumaran/delineate#1]
Hi Jeet,
I'm trying to use DELINEATE with an empirical dataset, but I'm getting different errors, and cannot figure out why.

(1) First, there seem to be a syntax error in the control.py ? 
I got this error:

> delineate-estimate partitions -t starbeast.nex --t Imap.txt
> Traceback (most recent call last):
>   File "/usr/local/bin/delineate-estimate", line 41, in <module>
>     from delineate import control
>   File "/Library/Python/2.7/site-packages/delineate/control.py", line 343
>     **self._logger_kwargs,
>                          ^
> SyntaxError: invalid syntax

The error doesn't show up any more after I removed the line 343 from control.py: **self._logger_kwargs,
I believe the ** intended to be a comment?
BUT, I'm not sure if by deleting this line, something is going to be problematic later.

(2) Now the program is starting, but I get a new error with treemodel.py, and I couldn't figure out why this is happening. Note that I get this same error if I use a nexus tree in data/speciation-completion-rate/s1-298db43

> delineate-estimate partitions -t starbeast.nex --t Imap.txt
> 
> [delineate-estimate 2020-02-14 12:54:51] 19 lineages found on population tree:
>     [  1/19 ] 'Apoast'    
>     [  2/19 ] 'Apocha'    
>     [  3/19 ] 'Aposup'    
>     [  4/19 ] 'Apofla'    
>     [  5/19 ] 'Apoglo'    
>     [  6/19 ] 'Apozal'    
>     [  7/19 ] 'AsLcit'    
>     [  8/19 ] 'AsMtol'    
>     [  9/19 ] 'Tsccit'    
>     [ 10/19 ] 'Ayecit'    
>     [ 11/19 ] 'Xilama'    
>     [ 12/19 ] 'Xilsag'    
>     [ 13/19 ] 'Xilxil'    
>     [ 14/19 ] 'Xilvir'    
>     [ 15/19 ] 'Mancit'    
>     [ 16/19 ] 'Manlab'    
>     [ 17/19 ] 'Mascit'    
>     [ 18/19 ] 'Niccit'    
>     [ 19/19 ] 'Niclab'    
> [delineate-estimate 2020-02-14 12:54:51] 19 lineages found in configuration file fully concordant with tree lineages
> [delineate-estimate 2020-02-14 12:54:51] 15 species defined in configuration constraints, with 15 lineages assigned:
>     [  1/15 ] 'Apoast'    (1 lineages)
>     [  2/15 ] 'Apocha'    (1 lineages)
>     [  3/15 ] 'Apofla'    (1 lineages)
>     [  4/15 ] 'Apoglo'    (1 lineages)
>     [  5/15 ] 'Aposup'    (1 lineages)
>     [  6/15 ] 'Apozal'    (1 lineages)
>     [  7/15 ] 'AsLcit'    (1 lineages)
>     [  8/15 ] 'AsMtol'    (1 lineages)
>     [  9/15 ] 'Ayecit'    (1 lineages)
>     [ 10/15 ] 'Mascit'    (1 lineages)
>     [ 11/15 ] 'Tsccit'    (1 lineages)
>     [ 12/15 ] 'Xilama'    (1 lineages)
>     [ 13/15 ] 'Xilsag'    (1 lineages)
>     [ 14/15 ] 'Xilvir'    (1 lineages)
>     [ 15/15 ] 'Xilxil'    (1 lineages)
> [delineate-estimate 2020-02-14 12:54:51] 15 out of 19 lineages assigned by constraints to 15 species:
>     [  1/15 ] 'Apoast'    (SPECIES: 'Apoast')
>     [  2/15 ] 'Apocha'    (SPECIES: 'Apocha')
>     [  3/15 ] 'Apofla'    (SPECIES: 'Apofla')
>     [  4/15 ] 'Apoglo'    (SPECIES: 'Apoglo')
>     [  5/15 ] 'Aposup'    (SPECIES: 'Aposup')
>     [  6/15 ] 'Apozal'    (SPECIES: 'Apozal')
>     [  7/15 ] 'AsLcit'    (SPECIES: 'AsLcit')
>     [  8/15 ] 'AsMtol'    (SPECIES: 'AsMtol')
>     [  9/15 ] 'Ayecit'    (SPECIES: 'Ayecit')
>     [ 10/15 ] 'Mascit'    (SPECIES: 'Mascit')
>     [ 11/15 ] 'Tsccit'    (SPECIES: 'Tsccit')
>     [ 12/15 ] 'Xilama'    (SPECIES: 'Xilama')
>     [ 13/15 ] 'Xilsag'    (SPECIES: 'Xilsag')
>     [ 14/15 ] 'Xilvir'    (SPECIES: 'Xilvir')
>     [ 15/15 ] 'Xilxil'    (SPECIES: 'Xilxil')
> [delineate-estimate 2020-02-14 12:54:51] 4 out of 19 lineages not constrained by species assignments:
>     [  1/4  ] 'Mancit'
>     [  2/4  ] 'Manlab'
>     [  3/4  ] 'Niccit'
>     [  4/4  ] 'Niclab'
> Traceback (most recent call last):
>   File "delineate-estimate", line 498, in <module>
>     main()
>   File "delineate-estimate", line 490, in main
>     args.func(args=args)
>   File "delineate-estimate", line 61, in execute_species_partition_estimation
>     labels=controller.constrained_lineage_leaf_labels)
>   File "/Library/Python/2.7/site-packages/dendropy/datamodel/treemodel.py", line 3533, in extract_tree_with_taxa_labels
>     is_apply_filter_to_internal_nodes=False,
>   File "/Library/Python/2.7/site-packages/dendropy/datamodel/treemodel.py", line 3404, in extract_tree
>     node_factory=node_factory,
>   File "/Library/Python/2.7/site-packages/dendropy/datamodel/treemodel.py", line 2267, in extract_subtree
>     nd1 = node_factory()
> TypeError: __init__() takes exactly 2 arguments (1 given)
> dhcp-m08-12:bin melisaolave$ python delineate-estimate partitions --tree-file starbeast-timeCalibrated.nex --config-file Imap.txt
> [delineate-estimate 2020-02-14 12:57:21] 19 lineages found on population tree:
>     [  1/19 ] 'Apoast'    
>     [  2/19 ] 'Apocha'    
>     [  3/19 ] 'Apofla'    
>     [  4/19 ] 'Apoglo'    
>     [  5/19 ] 'Aposup'    
>     [  6/19 ] 'Apozal'    
>     [  7/19 ] 'AsLcit'    
>     [  8/19 ] 'AsMtol'    
>     [  9/19 ] 'Ayecit'    
>     [ 10/19 ] 'Mancit'    
>     [ 11/19 ] 'Manlab'    
>     [ 12/19 ] 'Mascit'    
>     [ 13/19 ] 'Niccit'    
>     [ 14/19 ] 'Niclab'    
>     [ 15/19 ] 'Tsccit'    
>     [ 16/19 ] 'Xilama'    
>     [ 17/19 ] 'Xilsag'    
>     [ 18/19 ] 'Xilvir'    
>     [ 19/19 ] 'Xilxil'    
> [delineate-estimate 2020-02-14 12:57:21] 19 lineages found in configuration file fully concordant with tree lineages
> [delineate-estimate 2020-02-14 12:57:21] 15 species defined in configuration constraints, with 15 lineages assigned:
>     [  1/15 ] 'Apoast'    (1 lineages)
>     [  2/15 ] 'Apocha'    (1 lineages)
>     [  3/15 ] 'Apofla'    (1 lineages)
>     [  4/15 ] 'Apoglo'    (1 lineages)
>     [  5/15 ] 'Aposup'    (1 lineages)
>     [  6/15 ] 'Apozal'    (1 lineages)
>     [  7/15 ] 'AsLcit'    (1 lineages)
>     [  8/15 ] 'AsMtol'    (1 lineages)
>     [  9/15 ] 'Ayecit'    (1 lineages)
>     [ 10/15 ] 'Mascit'    (1 lineages)
>     [ 11/15 ] 'Tsccit'    (1 lineages)
>     [ 12/15 ] 'Xilama'    (1 lineages)
>     [ 13/15 ] 'Xilsag'    (1 lineages)
>     [ 14/15 ] 'Xilvir'    (1 lineages)
>     [ 15/15 ] 'Xilxil'    (1 lineages)
> [delineate-estimate 2020-02-14 12:57:21] 15 out of 19 lineages assigned by constraints to 15 species:
>     [  1/15 ] 'Apoast'    (SPECIES: 'Apoast')
>     [  2/15 ] 'Apocha'    (SPECIES: 'Apocha')
>     [  3/15 ] 'Apofla'    (SPECIES: 'Apofla')
>     [  4/15 ] 'Apoglo'    (SPECIES: 'Apoglo')
>     [  5/15 ] 'Aposup'    (SPECIES: 'Aposup')
>     [  6/15 ] 'Apozal'    (SPECIES: 'Apozal')
>     [  7/15 ] 'AsLcit'    (SPECIES: 'AsLcit')
>     [  8/15 ] 'AsMtol'    (SPECIES: 'AsMtol')
>     [  9/15 ] 'Ayecit'    (SPECIES: 'Ayecit')
>     [ 10/15 ] 'Mascit'    (SPECIES: 'Mascit')
>     [ 11/15 ] 'Tsccit'    (SPECIES: 'Tsccit')
>     [ 12/15 ] 'Xilama'    (SPECIES: 'Xilama')
>     [ 13/15 ] 'Xilsag'    (SPECIES: 'Xilsag')
>     [ 14/15 ] 'Xilvir'    (SPECIES: 'Xilvir')
>     [ 15/15 ] 'Xilxil'    (SPECIES: 'Xilxil')
> [delineate-estimate 2020-02-14 12:57:21] 4 out of 19 lineages not constrained by species assignments:
>     [  1/4  ] 'Mancit'
>     [  2/4  ] 'Manlab'
>     [  3/4  ] 'Niccit'
>     [  4/4  ] 'Niclab'
> Traceback (most recent call last):
>   File "delineate-estimate", line 498, in <module>
>     main()
>   File "delineate-estimate", line 490, in main
>     args.func(args=args)
>   File "delineate-estimate", line 61, in execute_species_partition_estimation
>     labels=controller.constrained_lineage_leaf_labels)
>   File "/Library/Python/2.7/site-packages/dendropy/datamodel/treemodel.py", line 3533, in extract_tree_with_taxa_labels
>     is_apply_filter_to_internal_nodes=False,
>   File "/Library/Python/2.7/site-packages/dendropy/datamodel/treemodel.py", line 3404, in extract_tree
>     node_factory=node_factory,
>   File "/Library/Python/2.7/site-packages/dendropy/datamodel/treemodel.py", line 2267, in extract_subtree
>     nd1 = node_factory()
> TypeError: __init__() takes exactly 2 arguments (1 given)
> 
> 

Thanks for your help!

Melisa

**Comment by jeetsukumaran** [comment]
Hi Melisa,

Sorry for the delay in getting to this. The issue is that you are running Python 2.7, and delineate requires Python 3.x.
